backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: uploads
locale: "de"
slug:
  encoding: "ascii"
  clean_accents: true
site_url: https://www.biohofkoch.com/
logo_url: /assets/images/logo.svg
extension: "json"
format: "json"
collections:
  - label: "Seiten"
    name: "pages"
    files:
      - label: "Startseite"
        name: "startseite"
        file: "content/startseite.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "Platzhalter"
        name: "platzhalter"
        file: "content/platzhalter.json"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Beschreibung", name: "description", widget: "text", pattern: [".{0,160}", "Maximal 160 Zeichen"] }
          - { label: "Hintergrundbild", name: "backgroundimage", widget: "image" }
          - { label: "Kontaktdaten", name: "contactdata", widget: "markdown" }
          - { label: "Facebook Link", name: "facebooklink", widget: "string" }
