backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: uploads
locale: "de"
slug:
  encoding: "ascii"
  clean_accents: true
site_url: https://www.biohofkoch.com/
logo_url: /assets/images/logo.svg
extension: "md"
editor:
  preview: false
collections:
  - label: "Seiten"
    name: "pages"
    files:
      - label: "Platzhalter"
        name: "platzhalter"
        file: "content/platzhalter.md"
        preview_path: "/"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Beschreibung", name: "description", widget: "text", pattern: [".{0,160}", "Maximal 160 Zeichen"] }
          - { label: "Hintergrundbild", name: "backgroundimage", widget: "image", media_library: { config: { multiple: true } } }
          - { label: "Kontaktdaten", name: "body", widget: "markdown" }
          - { label: "Facebook Link", name: "facebooklink", widget: "string" }
      - label: "Startseite"
        name: "startseite"
        file: "content/startseite.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Über uns"
        name: "ueber-uns"
        file: "content/ueber-uns.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Süße Knolle"
        name: "suesse-knolle"
        file: "content/suesse-knolle.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Hofladen & Gemüsekiste"
        name: "hofladen-gemuesekiste"
        file: "content/hofladen-gemuesekiste.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Presseartikel"
        name: "presseartikel"
        file: "content/presseartikel.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Kontakt"
        name: "kontakt"
        file: "content/kontakt.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
  - label: "Allgemein"
    name: "general"
    files:
      - label: "Footer"
        name: "footer"
        file: "content/footer.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Kontaktdaten", name: "contactdata", widget: "text" }
          - { label: "Standort", name: "location", widget: "map" }
          - { label: "Kontakt Titel", name: "contactdata", widget: "string" }
          - { label: "Email", name: "email", widget: "text" }
          - { label: "Telefonnummer", name: "tel", widget: "text" }
          - { label: "Facebook Titel", name: "facebooklink", widget: "string" }
          - { label: "Facebook Link", name: "facebooklink", widget: "string" }
      - label: "SEO"
        name: "seo"
        file: "content/seo.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
