backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: uploads
locale: "de"
slug:
  encoding: "ascii"
  clean_accents: true
site_url: https://www.biohofkoch.com/
logo_url: /assets/images/logo.svg
extension: "md"
collections:
  - label: "Seiten"
    name: "pages"
    preview: false
    files:
      - label: "Platzhalter"
        name: "platzhalter"
        file: "content/platzhalter.md"
        preview_path: "/"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Beschreibung", name: "description", widget: "text", pattern: [".{0,160}", "Maximal 160 Zeichen"] }
          - { label: "Hintergrundbild", name: "backgroundimage", widget: "image", media_library: { config: { multiple: true } } }
          - { label: "Kontaktdaten", name: "body", widget: "markdown" }
          - { label: "Facebook Link", name: "facebooklink", widget: "string" }
      - label: "Startseite"
        name: "startseite"
        file: "content/startseite.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Über uns"
        name: "ueber-uns"
        file: "content/ueber-uns.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Süße Knolle"
        name: "suesse-knolle"
        file: "content/suesse-knolle.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Hofladen & Bio Kiste"
        name: "hofladen-bio-kiste"
        file: "content/hofladen-bio-kiste.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Presseartikel"
        name: "presseartikel"
        file: "content/presseartikel.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
      - label: "Kontakt"
        name: "kontakt"
        file: "content/kontakt.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
  - label: "SEO"
    name: "seo"
    files:
      - label: "SEO"
        name: "seo"
        file: "content/seo.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
