backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: uploads
locale: 'de'
slug:
  encoding: 'ascii'
  clean_accents: true
site_url: https://www.biohofkoch.com/
logo_url: /assets/images/logo.svg
extension: 'md'
editor:
  preview: false
collections:
  - label: 'Seiten'
    name: 'pages'
    files:
      - label: 'Platzhalter'
        name: 'platzhalter'
        file: 'content/platzhalter.md'
        preview_path: '/'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Hintergrundbild', name: 'backgroundimage', widget: 'image', media_library: { config: { multiple: true } } }
          - { label: 'Kontaktdaten', name: 'body', widget: 'markdown' }
          - { label: 'Facebook Link', name: 'facebooklink', widget: 'string' }
      - label: 'Startseite'
        name: 'startseite'
        file: 'content/startseite.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
      - label: 'Über uns'
        name: 'ueber-uns'
        file: 'content/ueber-uns.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Einleitungstitel', name: 'heroHeader', widget: 'string' }
          - { label: 'Einleitungstext', name: 'heroText', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Einleitungsbild', name: 'heroImage', widget: 'image' }
          - label: 'Profile'
            label_singular: 'Profil'
            name: 'profiles'
            widget: 'list'
            allow_add: true
            collapsed: false
            min: 1
            fields:
              - { label: 'Name', name: 'profileName', widget: 'string' }
              - { label: 'Text', name: 'profileText', widget: 'string' }
              - { label: 'Zitat', name: 'profileQuote', widget: 'string' }
              - { label: 'Bild', name: 'profileImage', widget: 'image' }
              - { label: 'Invertiert', name: 'profileSwitch', widget: 'boolean', default: false, required: false }
          - { label: 'Titel 1', name: 'title1', widget: 'string' }
          - { label: 'Text 1', name: 'text1', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Bild 1', name: 'image1', widget: 'image' }
          - { label: 'Bild 2', name: 'image2', widget: 'image' }
          - { label: 'Titel 2', name: 'title2', widget: 'string' }
          - { label: 'Text 2', name: 'text2', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Bild 3', name: 'image3', widget: 'image' }
      - label: 'Süße Knolle'
        name: 'suesse-knolle'
        file: 'content/suesse-knolle.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Einleitungstitel', name: 'heroHeader', widget: 'string' }
          - { label: 'Einleitungstext', name: 'heroText', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Einleitungsbild', name: 'heroImage', widget: 'image' }
          - { label: 'Gallerie Text', name: 'galleryText', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Gallerie Bild', name: 'galleryImage', widget: 'image' }
          - { label: 'Versandtitel', name: 'shippingHeader', widget: 'string' }
          - { label: 'Versanttext 1', name: 'shippingText1', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Preise Titel', name: 'priceHeader', widget: 'string' }
          - label: 'Preis - Zeilen'
            label_singular: 'Preise - Zeile'
            name: 'priceitems'
            widget: 'list'
            allow_add: true
            collapsed: false
            min: 1
            fields:
              - { label: 'Menge', name: 'quantity', widget: 'string' }
              - { label: 'Preis', name: 'text', widget: 'string' }
          - { label: 'Versanttext 2', name: 'shippingText2', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Gallerie Bild 1', name: 'galleryImage1', widget: 'image' }
          - { label: 'Gallerie Bild 2', name: 'galleryImage2', widget: 'image' }
      - label: 'Bio-Frühkartoffeln'
        name: 'bio-fruehkartoffeln'
        file: 'content/bio-fruehkartoffeln.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Einleitungstitel', name: 'heroHeader', widget: 'string' }
          - { label: 'Einleitungstext', name: 'heroText', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Einleitungsbild', name: 'heroImage', widget: 'image' }
          - { label: 'Titel 1', name: 'title1', widget: 'string' }
          - { label: 'Text 1', name: 'text1', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Bild 1', name: 'image1', widget: 'image' }
          - { label: 'Bild 2', name: 'image2', widget: 'image' }
      - label: 'Hofladen'
        name: 'hofladen'
        file: 'content/hofladen.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Einleitungstitel', name: 'heroHeader', widget: 'string' }
          - { label: 'Einleitungstext', name: 'heroText', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Einleitungsbild', name: 'heroImage', widget: 'image' }
          - { label: 'Text 1', name: 'text1', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Bild 1', name: 'image1', widget: 'image' }
      - label: 'Presseartikel'
        name: 'presseartikel'
        file: 'content/presseartikel.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Einleitungstitel', name: 'heroHeader', widget: 'string' }
          - { label: 'Einleitungstext', name: 'heroText', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Einleitungsbild', name: 'heroImage', widget: 'image' }
          - label: 'Dateien'
            label_singular: 'Datei'
            name: 'files'
            widget: 'list'
            allow_add: true
            collapsed: false
            min: 1
            fields:
              - { label: 'Dateiname', name: 'quantity', widget: 'string' }
              - { label: 'Datei', name: 'file', widget: 'file' }
      - label: 'Kontakt'
        name: 'kontakt'
        file: 'content/kontakt.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Einleitungstitel', name: 'heroHeader', widget: 'string' }
          - { label: 'Einleitungstext', name: 'heroText', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Einleitungsbild', name: 'heroImage', widget: 'image' }
  - label: 'Allgemein'
    name: 'general'
    files:
      - label: 'Allgemein'
        name: 'general'
        file: 'content/general.md'
        fields:
          - { label: 'Titel (Suchmaschine)', name: 'title', widget: 'string' }
          - { label: 'Beschreibung (Suchmaschine)', name: 'description', widget: 'text', pattern: ['.{0,160}', 'Maximal 160 Zeichen'] }
          - { label: 'Bild (Teilen)', name: 'ogImage', widget: 'image' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Telefonnummer', name: 'tel', widget: 'string' }
          - { label: 'Facebook Titel', name: 'facebooktitle', widget: 'string' }
          - { label: 'Facebook Link', name: 'facebooklink', widget: 'string' }
      - label: 'Footer'
        name: 'footer'
        file: 'content/footer.md'
        fields:
          - { label: 'Kontakt Titel 1', name: 'contacttitle1', widget: 'string' }
          - { label: 'Kontaktdaten', name: 'contacttext', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
          - { label: 'Kontakt Titel 2', name: 'contacttitle2', widget: 'string' }
          - { label: 'Zertifikat Bild 1', name: 'certificateImage1', widget: 'image' }
          - { label: 'Zertifikat Bild 2', name: 'certificateImage2', widget: 'image' }
          - { label: 'Zertifikat Text', name: 'certificatetext', widget: 'markdown', modes: ['rich_text'], editor_components: [] }
